### ISSUE TITLE
Cannot find module ng-zendesk-webwidget

### ISSUE THREAD

**Issue by DaYuClo** [mackelito/ng-zendesk-webwidget#2]
I installed the package via npm then try to import it in the app.module

// cannot find module ng-zendesk-webwidget. ts(2307)
import { ngZendeskWebwidgetModule } from 'ng-zendesk-webwidget';

Angular 7.2 project

P.S. I can install and import ngx-zendesk-webwidget just fine.

**Comment by sriten** [comment]
I have the same issue.  And I figured out, the structure of this project is different to that of ngx-zendesk-webwidget.

**Comment by sriten** [comment]
If I import module like this, it then works. 
<img width="830" alt="image" src="https://user-images.githubusercontent.com/45519241/55196745-3827d180-51a8-11e9-83d6-55eab0ca174f.png">

The type exported form the module.d.ts is named as "ZendeskWebwidgetModule". Where as in the documentation, it is specified as "ngZendeskWebwidgetModule".

**Comment by DaYuClo** [comment]
@sriten Appreciate it.  Kudo!

**Comment by mackelito** [comment]
Sorry guys!.. forgot to update docs.. I have a new branch for some overall updates to the ReadMe...
@DaYuClo, @sriten so is it working for you guys? Can we close this issue?

**Comment by mackelito** [comment]
Will close this for now.. Let me know if it's not working

**Comment by sriten** [comment]
> Sorry guys!.. forgot to update docs.. I have a new branch for some overall updates to the ReadMe...
> @DaYuClo, @sriten so is it working for you guys? Can we close this issue?

I'm creating a local service for Zendesk activity using your repo for now. I'm going to update the service methods with all the other API functions available. I will then create a PR to update this repo. 

Cheers
