### ISSUE TITLE
ZendeskWebwidgetModule does not have a module def (ɵmod property) when upgrading to angular 16

### ISSUE THREAD

**Issue by edthompson-nf** [mackelito/ng-zendesk-webwidget#32]
When I try to upgrade to angular 16, I get the error define din the title.  Other packages resolved this when I upgraded to latest version, but not ng-zendesk-webwidget.  

Not sure how to proceed

**Comment by mackelito** [comment]
I'm sorry but this library is no longer maintained. But feel free to either fork it or create a PR
