### ISSUE TITLE
ZendeskWebwidget and server mode rendering

### ISSUE THREAD

**Issue by aonnen** [mackelito/ng-zendesk-webwidget#8]
Hy guys,

I try to execute zendesk module code on node.js with following exception

```
ReferenceError: window is not defined
    at getWindow (/Users/aonnen/work/dev/societeinfo/dist/server.js:306735:5)
    at new ngxZendeskWebwidgetService (/Users/aonnen/work/dev/societeinfo/dist/server.js:306743:23)
    at _createClass (/Users/aonnen/work/dev/societeinfo/dist/server.js:12389:20)

```

Naturally this comes from the ngxZendeskWebwidgetService  constructor

`  constructor(_ZendeskWebwidgetConfig?: ZendeskWebwidgetConfig) {
    if (!_ZendeskWebwidgetConfig.accountUrl) {
      throw new Error('Missing accountUrl. Please set in app config via ZendeskWidgetProvider');
    }
    this.window = getWindow()
    let window = this.window`

Have you any idea of how to manage it ?
A little field in ZendeskWebwidgetConfig to manage this case could really help me

Thanks !

**Comment by mackelito** [comment]
Are you doing SSR? (ServerSideRendering) then there is no window object.
I have not tried this using angular universal or similar..

did a quick googling.. perhaps this helps?
https://stackoverflow.com/questions/52391718/angular-6-server-side-rendering-issue-window-not-defined

**Comment by mackelito** [comment]
Closing this issue.. let me know if you think it should be reopened :)
