### ISSUE TITLE
Updating Settings doesn't work

### ISSUE THREAD

**Issue by FatManiac** [mackelito/ng-zendesk-webwidget#9]
Hi,

first thank you for this fork since the original one appear to be a ghost :)

I try to change tag depending on where i am on my website. For that i just use setSettings and put the new tags that i want. Problem is, it doesn't work, my tags doesn't change on zendesk.
Is it working for anybody and i just don't use it the right way ?

**Comment by mackelito** [comment]
Would you mind sharing some code? :)

**Comment by FatManiac** [comment]
This is the function that i use to set Zendesk settings

`  setZendesk(questionTag: boolean, fName: string = null, lName: string = null, email: string = null) {
    if (!!fName && !! lName && !!email) {
      this.zendeskService.identify({
        name: `${fName} ${lName}`,
        email: email
      })
    }
    const settings = {
      webWidget: {
        position: {
          horizontal: 'left'
        },
        contactForm: {
          tags: questionTag ? ['app', 'questions_code'] : ['app']
        },
        offset: {
          mobile: {
            horizontal: '230px',
            vertical: '100px'
          }
        }
      }
    }
    this.zendeskService.setSettings(settings)
  }
`

when i check ZEsettings, the tags change but on zendesk the tag that i get is the tag that is set first, so if i start the app and the tag is 'app' even if i update the tags it stay to 'app'

**Comment by mackelito** [comment]
First I would suggest to split it into 2 methods.
One to identify the user and second to update settings...

The tags object is for v2 of the api and this plugin uses v1 (https://developer.zendesk.com/embeddables/docs/widget/api) so there is no option to set tags.

Right now I have not started any work migrating to v2 but any PR's are welcome :)

**Comment by FatManiac** [comment]
thanks for the clearance
